modules:
  chefs:
    name: Chef
    model: KepplerStaffChef
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  waiters:
    name: Waiter
    model: KepplerStaffWaiter
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
