menu:
  keppler_environments:
    name: Keppler Environments
    current: ['/admin/environments/sections']
    url_path: /admin/environments/sections
    icon: layout
    model: KepplerEnvironments::Section
    environment: all
    position: 4
