menu:
  keppler_orders:
    name: Keppler Orders
    current: ['/admin/orders/orders']
    url_path: /admin/orders/orders
    icon: rocket
    model: KepplerOrders::Order
    environment: all
    position: 4
