modules:
  items:
    name: Item
    model: KepplerOrdersItem
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  orders:
    name: Order
    model: KepplerOrdersOrder
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
